[package]
name = "crb-core-web"
description = "CRB | Composable Runtime Blocks | WEB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
#web-time = "1.1.0"
tokio = { version = "1.43.0", features = ["sync"] }
wasm-bindgen-futures = "0.4.50"
wasmtimer = "0.4.1"
futures.workspace = true
thiserror.workspace = true
uuid = { version = "1.15.0", default-features = false, features = ["v4", "v5", "serde", "js"] }

# gloo-timers = { version = "0.3.0", features = ["futures"] }
# ordered-float = { version = "4.6.0", default-features = false }
# js-sys = "0.3.77"
# web-sys = { version = "0.3.77", features = ["Performance", "Window"] }
