[workspace]
resolver = "2"
members = [
    "crates/*",
]
exclude = [
    "examples"
]

[workspace.package]
version = "0.0.33"
edition = "2021"
license = "MIT"
repository = "https://github.com/runtime-blocks/crb"

[workspace.dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
crb-agent = { version = "0.0.33", path = "crates/crb-agent", default-features = false }
crb-superagent = { version = "0.0.33", path = "crates/crb-superagent", default-features = false }
crb-core = { version = "0.0.33", path = "crates/crb-core", default-features = false }
crb-runtime = { version = "0.0.33", path = "crates/crb-runtime", default-features = false }
crb-send = { version = "0.0.33", path = "crates/crb-send" }
crb-system = { version = "0.0.33", path = "crates/crb-system" }
derive_more = { version = "2.0.1", features = ["full"] }
futures = "0.3.31"
futures-util = "0.3.31"
log = "0.4.27"
thiserror = "2.0.12"
tokio = { version = "1.44.2" }
tokio-stream = "0.1.17"
typed-slab = "0.2.1"
