[package]
name = "crb-core"
description = "CRB | Composable Runtime Blocks | Core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
futures.workspace = true
thiserror.workspace = true
crb-core-web.path = "../crb-core-web"
tokio = { workspace = true, features = ["sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crb-core-std.path = "../crb-core-std"

[target.'cfg(target_arch = "wasm32")'.dependencies]
crb-core-web.path = "../crb-core-web"

[features]
std = []
web = []
