[package]
name = "crb-core"
description = "CRB | Composable Runtime Blocks | Core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
futures.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
crb-core-std = { path = "../crb-core-std", optional = true }
crb-core-web = { path = "../crb-core-web", optional = true }

[features]
std = ["crb-core-std"]
web = ["crb-core-web"]
