[package]
name = "web-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
async-trait = "0.1.86"
console_error_panic_hook = "0.1.7"
crb = { path = "../../crates/crb", default-features = false, features = ["web"] }
log = "0.4.26"
tokio-stream = "0.1.17"
wasm-logger = "0.2.0"
yew = { version = "0.21.0", features = ["csr"] }
